version: '3.7'

services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: always
        env_file:
            - .env
        ports:
            - 27017:27017
        volumes:
            - mongo-data:/data/db
            - ./db-initial-script/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
volumes:
    mongo-data: